In [743]:
import pandas as pd
import numpy as np
import calendar

## Задание 1.
1. Скачать данные - недвижимость (в закрепе к уроку).
2. Считать данные с помощью pandas
3. Вывести на экран первые 5 строк

In [744]:
df = pd.read_csv('kc_house_data.csv', encoding='latin-1', sep=',')

In [745]:
df.sort_values('sqft_lot').head(25)

id             date      price  bedrooms  bathrooms  \
15743  9828702895  20141022T000000   700000.0         4       1.75   
5826   1773101159  20150107T000000   250000.0         3       2.25   
7589   6371000026  20150122T000000   367500.0         2       2.00   
3452   2559950110  20150422T000000  1234570.0         2       2.50   
20604  7899800857  20141215T000000   256950.0         2       2.00   
21552   688000017  20140627T000000   516500.0         1       1.25   
547    7899800860  20150319T000000   259950.0         2       2.00   
4352   7899800864  20150305T000000   259950.0         2       2.00   
19662  3362400125  20150303T000000   405000.0         3       2.00   
21519  1702901618  20150407T000000   420000.0         1       2.00   
7213   3319500299  20140806T000000   304000.0         2       1.50   
21381  9521100301  20140507T000000   339950.0         2       1.00   
20095  8562780490  20150223T000000   335000.0         3       2.50   
15669  9828702335  20150212T000000   570000.0         2       2.00   
20994  1972201772  20150409T000000   650000.0         2       2.50   
20744  1604601572  20140905T000000   345000.0         2       2.25   
21137  8562780430  20150504T000000   346100.0         2       1.75   
10612  3259400024  20150427T000000   340000.0         3       2.00   
18010  7234601198  20140604T000000   742000.0         3       3.25   
21109  8562780190  20141007T000000   315000.0         2       2.25   
20731  8562780200  20150427T000000   352499.0         2       2.25   
20907  8562780540  20141222T000000   325000.0         2       2.25   
21015  8562780530  20150328T000000   338500.0         2       2.25   
20567  6926700654  20140921T000000   700000.0         2       2.00   
21307  8562780280  20150220T000000   331000.0         2       2.25   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
15743         2420       520     1.5           0     0  ...      7   
5826          1050       572     2.0           0     0  ...      7   
7589          1030       600     2.0           0     0  ...      8   
3452          2470       609     3.0           0     0  ...     11   
20604         1070       635     2.0           0     0  ...      9   
21552         1100       638     3.0           0     0  ...      9   
547           1070       649     2.0           0     0  ...      9   
4352          1070       649     2.0           0     0  ...      9   
19662         1060       651     3.0           0     0  ...      7   
21519         1070       675     2.0           0     0  ...      8   
7213           950       676     2.0           0     0  ...      7   
21381          820       681     3.0           0     0  ...      8   
20095         1150       683     2.0           0     0  ...      7   
15669         1140       690     2.0           0     0  ...      8   
20994         1470       690     3.0           0     3  ...      8   
20744          860       696     2.0           0     0  ...      9   
21137         1150       698     2.0           0     0  ...      7   
10612         1150       700     2.0           0     0  ...      7   
18010         1540       704     3.0           0     0  ...      9   
21109         1240       705     2.0           0     0  ...      7   
20731         1240       705     2.0           0     0  ...      7   
20907         1150       711     2.0           0     0  ...      7   
21015         1150       711     2.0           0     0  ...      7   
20567         1490       713     3.0           0     0  ...      9   
21307         1240       720     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
15743        2420              0      1900             0    98112  47.6209   
5826          740            310      2006             0    98106  47.5549   
7589          680            350      2004             0    98116  47.5788   
3452         1910            560      2011             0    9

In [746]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

    1.1 Создать новый признак price_per_sq_lot, который будет содержать среднюю стоимость за один кв. метр общей площади

In [747]:
df['price_specific_area']=df['price']/df['sqft_lot']

In [748]:
df[['price','sqft_lot','price_specific_area']].sort_values('sqft_lot').head(15)

price  sqft_lot  price_specific_area
15743   700000.0       520          1346.153846
5826    250000.0       572           437.062937
7589    367500.0       600           612.500000
3452   1234570.0       609          2027.208539
20604   256950.0       635           404.645669
21552   516500.0       638           809.561129
547     259950.0       649           400.539291
4352    259950.0       649           400.539291
19662   405000.0       651           622.119816
21519   420000.0       675           622.222222
7213    304000.0       676           449.704142
21381   339950.0       681           499.192364
20095   335000.0       683           490.483163
15669   570000.0       690           826.086957
20994   650000.0       690           942.028986

In [749]:
df['sqft_lot'].nunique()

9782

In [750]:
df['sqft_lot'].value_counts()

5000     358
6000     290
4000     251
7200     220
4800     120
        ... 
25248      1
9934       1
9142       1
24330      1
1076       1
Name: sqft_lot, Length: 9782, dtype: int64

In [751]:
df['price_specific_area'].values

array([ 39.27433628,  74.28887048,  18.        , ..., 297.85259259,
       167.5041876 , 302.04460967])

In [752]:
price_per_sq_lot = df.groupby('sqft_lot').agg({'price_specific_area' : 'mean'})
price_per_sq_lot[0:1].values

array([[1346.15384615]])

In [753]:
price_per_sq_lot.head(25)

price_specific_area
sqft_lot                     
520               1346.153846
572                437.062937
600                612.500000
609               2027.208539
635                404.645669
638                809.561129
649                400.539291
651                622.119816
675                622.222222
676                449.704142
681                499.192364
683                490.483163
690                884.057971
696                495.689655
698                495.845272
700                485.714286
704               1053.977273
705                473.403546
711                466.596343
713                981.767181
720                459.722222
725                588.965517
736                521.739130
740                824.324324
745                396.542953

In [754]:
age_days = []
value_squ = 0
for i, row in df.iterrows():
    if row['sqft_lot'] in price_per_sq_lot.index:
        value_squ = age_days.append(price_per_sq_lot[i:i+1].values)
    else:
        age_days.append(value_squ)

age_days[0:10]

[array([[1346.15384615]]),
 array([[437.06293706]]),
 array([[612.5]]),
 array([[2027.20853859]]),
 array([[404.64566929]]),
 array([[809.56112853]]),
 array([[400.53929122]]),
 array([[622.11981567]]),
 array([[622.22222222]]),
 array([[449.70414201]])]

In [755]:
df['price_per_sq_lot'] = age_days

In [756]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  sqft_basement  yr_built  \
0      5650     1.0           0     0  ...              0      1955   
1      7242     2.0           0     0  ...            400      1951   
2     10000     1.0           0     0  ...              0      1933   
3      5000     1.0           0     0  ...            910      1965   
4      8080     1.0           0     0  ...              0      1987   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0             0    98178  47.5112 -122.257           1340        5650   
1          1991    98125  47.7210 -122.319           1690        7639   
2             0    98028  47.7379 -122.233           2720        8062   
3             0    98136  47.5208 -122.393           1360        5000   
4             0    98074  47.6168 -122.045           1800        7503   

   price_specific_area        price_per_sq_lot  
0            39.274336  [[1346.1538461538462]]  
1            74.288870  [[437.06293706293707]]  
2            18.000000               [[612.5]]  
3           120.800000   [[2027.208538587849]]  
4            63.118812   [[404.6456692913386]]  

[5 rows x 23 columns]

    1.2 Создать новый признак delta_renovated, который будет содержать разницу в годах между годом реновацией дома и годом постройки дома.
    Если реновации дома не было, то в новом признаке поставьте 0

In [757]:
df['delta_renovated'] = 0

In [758]:
df.loc[df['yr_renovated'] != 0, 'delta_renovated'] = df['yr_renovated'] - df['yr_built']

In [759]:
df.delta_renovated.sort_values()

0          0
14285      0
14284      0
14283      0
14282      0
        ... 
586      110
6671     113
2566     114
15046    114
11695    114
Name: delta_renovated, Length: 21613, dtype: int64

    1.3 Создайте признаки года продажи, месяца продажи

In [760]:
df['date'] = pd.to_datetime(df['date'])
df['year_sale'] = df['date'].apply(lambda x: x.date().year)
df['month_sale'] = df['date'].apply(lambda x: x.date().month)
d = dict(enumerate(calendar.month_abbr))
df['month_sale'] = df['month_sale'].map(d)
df.sample(5)

id       date     price  bedrooms  bathrooms  sqft_living  \
5440  7215720250 2014-12-10  693000.0         4       2.50         3160   
1393  5100401414 2014-05-02  490000.0         2       1.00          880   
728   2525000510 2014-11-06  328000.0         3       1.75         1470   
776   2612000390 2014-06-15  269950.0         3       2.50         1890   
2722  7203101580 2014-07-24  410000.0         3       2.50         1740   

      sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
5440     13063     2.0           0     0  ...    98075  47.5996 -122.021   
1393      6380     1.0           0     0  ...    98115  47.6924 -122.322   
728       7650     1.0           0     0  ...    98059  47.4818 -122.161   
776       4838     2.0           0     0  ...    98168  47.4802 -122.279   
2722      4948     2.0           0     0  ...    98053  47.6966 -122.025   

      sqft_living15  sqft_lot15  price_specific_area        price_per_sq_lot  \
5440           3350       14213            53.050601  [[34.911961141469334]]   
1393           1340        6380            76.802508   [[196.7930029154519]]   
728            1590        7500            42.875817  [[239.88366211431463]]   
776            1910        7409            55.797850  [[125.08258612553091]]   
2722           1290        3383            82.861762   [[65.13828238719067]]   

      delta_renovated  year_sale  month_sale  
5440                0       2014         Dec  
1393               56       2014         May  
728                 0       2014         Nov  
776                 0       2014         Jun  
2722                0       2014         Jul  

[5 rows x 26 columns]

    1.4 Удалите признаки date, zipcode, lat, long

In [761]:
df.drop(columns=['date', 'zipcode', 'lat', 'long'], inplace=True)

In [762]:
df.head()

id     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  7129300520  221900.0         3       1.00         1180      5650     1.0   
1  6414100192  538000.0         3       2.25         2570      7242     2.0   
2  5631500400  180000.0         2       1.00          770     10000     1.0   
3  2487200875  604000.0         4       3.00         1960      5000     1.0   
4  1954400510  510000.0         3       2.00         1680      8080     1.0   

   waterfront  view  condition  ...  sqft_basement  yr_built  yr_renovated  \
0           0     0          3  ...              0      1955             0   
1           0     0          3  ...            400      1951          1991   
2           0     0          3  ...              0      1933             0   
3           0     0          5  ...            910      1965             0   
4           0     0          3  ...              0      1987             0   

   sqft_living15  sqft_lot15  price_specific_area        price_per_sq_lot  \
0           1340        5650            39.274336  [[1346.1538461538462]]   
1           1690        7639            74.288870  [[437.06293706293707]]   
2           2720        8062            18.000000               [[612.5]]   
3           1360        5000           120.800000   [[2027.208538587849]]   
4           1800        7503            63.118812   [[404.6456692913386]]   

   delta_renovated year_sale  month_sale  
0                0      2014         Oct  
1               40      2014         Dec  
2                0      2015         Feb  
3                0      2014         Dec  
4                0      2015         Feb  

[5 rows x 22 columns]

## Задание 2.
Создайте датафрейм с клиентами:

In [763]:
clients = pd.DataFrame({
'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295, 939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242, 2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],
'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300, 7137950720, 9510920050, 6131600255, 5428000070, 1788800910, 8100400160, 3123049142, 6306800010, 5083000375, 7920100025, 1951600150, 809001400, 339600110, 1622049154, 1099600250, 8563000110, 2768100205, 3995700435, 8861700030, 3303980210, 7731100066, 8146100580, 825069097, 3889100029, 9524100196]
})

In [764]:
clients_house_id = clients.set_index('house_id')

In [765]:
clients_house_id.head()

client_id
house_id             
8965450190       1459
6823100225       4684
5104540330       3498
2131701075       3942
1522700060       4535

In [766]:
df_idx = df.set_index('id')

In [767]:
df_idx.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
id                                                                         
7129300520  221900.0         3       1.00         1180      5650     1.0   
6414100192  538000.0         3       2.25         2570      7242     2.0   
5631500400  180000.0         2       1.00          770     10000     1.0   
2487200875  604000.0         4       3.00         1960      5000     1.0   
1954400510  510000.0         3       2.00         1680      8080     1.0   

            waterfront  view  condition  grade  ...  sqft_basement  yr_built  \
id                                              ...                            
7129300520           0     0          3      7  ...              0      1955   
6414100192           0     0          3      7  ...            400      1951   
5631500400           0     0          3      6  ...              0      1933   
2487200875           0     0          5      7  ...            910      1965   
1954400510           0     0          3      8  ...              0      1987   

            yr_renovated  sqft_living15  sqft_lot15  price_specific_area  \
id                                                                         
7129300520             0           1340        5650            39.274336   
6414100192          1991           1690        7639            74.288870   
5631500400             0           2720        8062            18.000000   
2487200875             0           1360        5000           120.800000   
1954400510             0           1800        7503            63.118812   

                  price_per_sq_lot delta_renovated  year_sale  month_sale  
id                                                                         
7129300520  [[1346.1538461538462]]               0       2014         Oct  
6414100192  [[437.06293706293707]]              40       2014         Dec  
5631500400               [[612.5]]               0       2015         Feb  
2487200875   [[2027.208538587849]]               0       2014         Dec  
1954400510   [[404.6456692913386]]               0       2015         Feb  

[5 rows x 21 columns]

    2.1 Присоедините к таблице clients данные по домам через метод join

In [768]:
joined = clients_house_id.join(df_idx)

In [769]:
joined.head()

client_id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
339600110        4809  395000.0         3       2.50         1610      3755   
809001400        3113  925000.0         3       1.00         1630      3200   
825069097        1764  770000.0         3       2.50         2650     40705   
1099600250       2242  260000.0         3       1.75         1710      6400   
1189000207       2308  387000.0         2       2.50         1170      1394   

            floors  waterfront  view  condition  ...  sqft_basement  yr_built  \
339600110      2.0           0     0          3  ...              0      1987   
809001400      1.5           0     0          4  ...              0      1912   
825069097      2.0           0     0          3  ...              0      1994   
1099600250     1.0           0     0          4  ...            470      1976   
1189000207     2.0           0     0          3  ...              0      2001   

            yr_renovated  sqft_living15  sqft_lot15  price_specific_area  \
339600110              0           1300        3823           105.193076   
809001400              0           1710        3600           289.062500   
825069097              0           2550       42625            18.916595   
1099600250             0           1600        6400            40.625000   
1189000207             0           1250        3136           277.618364   

                  price_per_sq_lot  delta_renovated year_sale  month_sale  
339600110    [[89.08170643528561]]                0      2014         Sep  
809001400   [[5.1652892561983474]]                0      2014         Sep  
825069097    [[97.51911374629428]]                0      2014         Jun  
1099600250   [[289.5985841846995]]                0      2014         Dec  
1189000207   [[28.79377431906615]]                0      2014         Oct  

[5 rows x 22 columns]

    2.2 Присоедините к таблице clients данные по домам через метод merge.
    Это нужно, чтобы понимать, какие дома покупались клиентами house_id - это индексы датафрейма с домами.

In [770]:
merged = clients.merge(df, left_on = 'house_id', right_on = 'id')

In [771]:
merged.head()

client_id    house_id          id     price  bedrooms  bathrooms  \
0       1459  8965450190  8965450190  295000.0         3       2.50   
1       4684  6823100225  6823100225  700000.0         4       1.75   
2       3498  5104540330  5104540330  679000.0         4       2.50   
3       3942  2131701075  2131701075  420000.0         3       1.75   
4       4535  1522700060  1522700060  518000.0         4       2.75   

   sqft_living  sqft_lot  floors  waterfront  ...  sqft_basement  yr_built  \
0         1500      3060     2.0           0  ...              0      1994   
1         1870      6000     1.0           0  ...            200      1949   
2         3680      7236     2.0           0  ...              0      2006   
3         1720      5000     1.5           0  ...              0      1932   
4         2520     14021     2.0           0  ...              0      1999   

   yr_renovated  sqft_living15  sqft_lot15  price_specific_area  \
0             0           2700        7734            96.405229   
1             0           1710        6000           116.666667   
2             0           3310        7180            93.836374   
3          2009           1410        8300            84.000000   
4             0           2330       14007            36.944583   

         price_per_sq_lot  delta_renovated  year_sale  month_sale  
0  [[25.726195128305328]]                0       2015         Feb  
1                      []                0       2015         Apr  
2    [[83.1247765462996]]                0       2015         May  
3                      []               77       2014         Dec  
4                      []                0       2014         Jun  

[5 rows x 24 columns]

## Задание 3.
Составьте несколько сводных таблиц:

    3.1 Найдите среднюю стоимость домов в зависимости от количества спален. Отсортируйте от меньшей стоимости к большей

In [772]:
df.groupby('bedrooms').agg({'price': 'mean'}).sort_values('price').apply(lambda x: round(x / 1000,0))

price
bedrooms        
1          318.0
2          401.0
0          410.0
3          466.0
11         520.0
4          635.0
33         640.0
5          787.0
10         819.0
6          826.0
9          894.0
7          951.0
8         1105.0

    3.2 Найдите минимальную, среднюю и максимальную стоимости домов в зависимости от состояния дома

In [773]:
group_data = df.groupby('condition').agg({'price': ['min', 'mean', 'max']}).head()

In [774]:
cols_list = group_data.columns.to_list()

In [775]:
group_data.sort_values(cols_list[2])

price                          
                min           mean        max
condition                                    
1           78000.0  334431.666667  1500000.0
2           80000.0  327287.145349  2555000.0
5          110000.0  612418.089359  3650000.0
3           75000.0  542012.578148  7062500.0
4           89000.0  521200.390033  7700000.0

    3.3 Постройте таблицу с подсчетом количества домов в данных в зависимости от вида на набережную и оценкой вида

In [776]:
df.pivot_table(index='waterfront', columns='view',
               values='condition', aggfunc='count',
               fill_value=0)

view            0    1    2    3    4
waterfront                           
0           19489  331  955  491  184
1               0    1    8   19  135

    3.4 Каких домов в зависимости от этажности и количества спален больше?

In [777]:
def highlight_max(x):
    return np.where(x == np.max(x.to_numpy()), f'color: blue ;', None)

In [778]:
df.pivot_table(index='floors',
               columns='bedrooms',
               values='id',
               aggfunc='count',
              fill_value=0).style.apply(highlight_max, axis=1)

    3.5 Постройте таблицу с подсчетом медианной стоимости домов в данных в зависимости от состояния дома и оценки дома

In [779]:
df.pivot_table(index='condition',
               columns='grade',
               values='price',
               aggfunc='median',
               fill_value=0)

grade          1       3       4       5       6       7       8        9   \
condition                                                                    
1          142000       0  150000  190000  255000  403500  932500        0   
2               0  280000  145000  180000  235000  305000  429000   715000   
3               0   75000  205000  234475  265000  357500  485000   689000   
4               0       0  238525  229975  295000  390000  571250   823500   
5               0  262000       0  227450  285475  456000  696000  1078000   

grade           10       11       12       13  
condition                                      
1                0        0        0        0  
2          1752500        0        0        0  
3           890000  1209500  1807500  2888000  
4          1030000  1685000  2125000  5750000  
5          1650000  2050000  1990000        0